theme = "swamp light"
client_id = "b60844fa1c1b48e3bc1b77f530ba02a1"
client_port = 8080
playback_format = "{track} â€¢ {artists}\n{album}\n{metadata}"

tracks_playback_limit = 50
app_refresh_duration_in_ms = 50
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20

play_icon = "|>"
pause_icon = "||"
liked_icon = "<3"
border_type = "Plain"
progress_bar_type = "Rectangle"

enable_media_control = true
enable_streaming = "Always"
enable_notify = true
default_device = "sharktooth"
notify_streaming_only = false

enable_cover_image_cache = true
cover_img_width = 5
cover_img_length = 10
cover_img_scale = 2.2

[notify_format]
summary = "{track}"
body = "{artists}"

[device]
name = "sharktooth"
device_type = "computer"
volume = 75
bitrate = 320
audio_cache = false
normalization = false

[layout]
library = { album_percent = 40, playlist_percent = 40 }
playback_window_position = "Bottom"
playback_window_height = 4
